# ============================================================
# Environment: Production
# File: src/main/resources/configs/prod.properties
# CAUTION: Only Smoke tests should run against Production
# ============================================================

env=prod
ui.base.url=https://www.saucedemo.com
api.base.url=https://petstore.swagger.io/v2
browser=chrome
headless=true
implicit.wait=20
explicit.wait=40
page.load.timeout=60
ui.username=standard_user
ui.password=secret_sauce
api.content.type=application/json
api.connection.timeout=20000
screenshot.on.failure=true
report.dir=test-output/extent-reports
