# ============================================================
# Environment: QA
# File: src/main/resources/configs/qa.properties
# ============================================================

env=qa
ui.base.url=https://www.saucedemo.com
api.base.url=https://petstore.swagger.io/v2
browser=chrome
headless=false
implicit.wait=10
explicit.wait=20
page.load.timeout=30
ui.username=standard_user
ui.password=secret_sauce
api.content.type=application/json
api.connection.timeout=10000
screenshot.on.failure=true
report.dir=test-output/extent-reports
